site_name: React Bootstrap Table
site_url: https://pallassystems.github.io/react-bootstrap-table/
site_description: Library to build responsive tables using the Bootstrap framework and React.
site_author: Pallas Systems

repo_url: https://github.com/PallasSystems/react-bootstrap-table

theme:
  name: bootstrap
  logo: images/logos/topbar-logo.png

extra_css:
  - css/bootstrap.solar.css
  - css/bootstrap.pallas.css
  - css/bootstrap.mkdocs.css

nav:
  - 'Getting Started':
      - 'Install': gettingstarted/install.md
  - 'API Reference': api/index.md
  - 'Examples': examples/index.md
